### ISSUE TITLE
Ability to tag multiple creators of a resource.

### ISSUE THREAD

**Issue by dstrukt** [Bitcoiners-Best/bitcoinersbest#130]
![paste (1)](https://user-images.githubusercontent.com/6250771/74407911-e2700e00-4de7-11ea-9b25-28ce53b82fff.png)
![paste](https://user-images.githubusercontent.com/6250771/74407913-e3a13b00-4de7-11ea-945a-d1519d3ec396.png)

**Comment by heelhook** [comment]
Being tracked on WIP PR #173.
