### ISSUE TITLE
500 error on admin "edit" resources

### ISSUE THREAD

**Issue by dstrukt** [Bitcoiners-Best/bitcoinersbest#135]
Experienced this issue somewhat randomly, but mostly on twitter threads and books.

![Screen+Recording+2020-02-13+at+12 53+AM](https://user-images.githubusercontent.com/6250771/74409854-79d76000-4dec-11ea-9be1-811941250959.gif)

**Comment by heelhook** [comment]
Yes, the issue was on twitter threads, books and articles. cb9320cd413b5556c16f53fee5a33aee0e689ccc fixes this.
