### ISSUE TITLE
Fix mobile logout link

### ISSUE THREAD

**Issue by dstrukt** [Bitcoiners-Best/bitcoinersbest#143]
Current:

<li class="menu-nav__li"><a href="<%= link_to 'Logout', destroy_user_session_path, method: :delete %>" class="a-h -ss-01"><h2>Logout</h2></a></li>

i noticed i botched the formatting for logout on mobile ..  i know i could add the class to that easily, but it's slightly different from desktop (just an a href tag), this has a nested h2 .. am i missing anything?

**Comment by heelhook** [comment]
Not sure why that `<h2>` was there, but it looks like `.menu-nav__li .a-h` were getting a `font-size` of `0`. Fixed it.
