### ISSUE TITLE
Doxing email addresses

### ISSUE THREAD

**Issue by Chaka321** [Bitcoiners-Best/bitcoinersbest#167]
If you leave the username blank on signup, it is falling through to displaying email addresses publicly on the site.

**Comment by heelhook** [comment]
hmm, yeah, that's definitely not good. Going to fix that asap.

**Comment by heelhook** [comment]
@Chaka321 this is now fixed retroactively, so users that didn't provide a name are now displayed as "anonymous".

Thanks for reporting!
