### ISSUE TITLE
"active" class highlighted when viewing the corresponding page

### ISSUE THREAD

**Issue by dstrukt** [Bitcoiners-Best/bitcoinersbest#96]
<img width="1649" alt="Screen Shot 2020-02-10 at 4 31 15 AM" src="https://user-images.githubusercontent.com/6250771/74150216-4c0cd400-4bbe-11ea-9aef-081c11f43a83.png">

Where the active element should be

**Comment by heelhook** [comment]
closed by b87602676556e2cf2ad333adf8dd447011fc9317
